groups:
- name: ApplicationAlerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_server_requests_seconds_count{status="5xx"}[5m]) > 0.1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: アプリケーションで5xxエラーの発生率が急上昇しています
